### ISSUE TITLE
netease.py 脚本报错

### ISSUE THREAD

**Issue by zhongwangninja** [Oreomeow/VIP#9]
python netease.py 报错如下
```shell
Traceback (most recent call last):
  File "/root/jd/scripts/netease.py", line 488, in <module>
    main_handler("", "")
  File "/root/jd/scripts/netease.py", line 484, in main_handler
    start()
  File "/root/jd/scripts/netease.py", line 477, in start
    if NETEASE_USER and NETEASE_PWD in os.environ:
NameError: name 'NETEASE_USER' is not defined
```

这处代码对环境变量`NETEASE_USER`的判断貌似应该对`NETEASE_USER`添加引号才能正确执行
```python
def start():
    if NETEASE_USER and NETEASE_PWD in os.environ:
        tasks_pool(get_envs())
    else:
        tasks_pool(get_args())
```

**Comment by ghost** [comment]
已修复
